export { Template } from "./template";

export const defaultSections = [
  {
    type: "contact",
    title: "",
    column: 1,
    order: 0,
    disabled: true,
    appear: true,
    required: true,
    removable: false,
  },
  {
    type: "summary",
    title: "Sumário",
    column: 1,
    order: 1,
    disabled: false,
    appear: true,
    required: true,
    removable: false,
  },
  {
    type: "skills",
    title: "Habilidades",
    column: 1,
    order: 2,
    disabled: false,
    appear: true,
    required: true,
    removable: false,
  },
  {
    type: "experiences",
    title: "Experiências",
    column: 1,
    order: 3,
    disabled: false,
    appear: true,
    required: true,
    removable: false,
  },
  {
    type: "educations",
    title: "Educações",
    column: 1,
    order: 4,
    disabled: false,
    appear: true,
    required: true,
    removable: false,
  },
];
